# Generated by Django 3.1 on 2020-10-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0002_auto_20201017_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='title',
            new_name='subject',
        ),
    ]
