# Generated by Django 3.1 on 2020-10-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0003_auto_20201017_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Contact',
        ),
    ]
