# Generated by Django 3.1 on 2020-10-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0004_auto_20201017_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
