# Generated by Django 3.1 on 2020-10-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundraiser', '0005_auto_20201017_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='fundraiser.campaign'),
        ),
    ]
